version: '2'
services:
  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - elasticsearch1
      - kibana
      - graylog
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    - 443:443
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    container_name: mongodb
    volumes:
      - gl_mongo_data:/data/db
    networks:
      - glnet
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.13
    container_name: elasticsearch1
    hostname: elasticsearch1
    environment:
        - cluster.name=graylog-cluster
        - bootstrap.memory_lock=true
        - xpack.security.enabled=false
        - xpack.watcher.enabled=false
        - xpack.monitoring.enabled=true
        - xpack.security.audit.enabled=false
        - xpack.ml.enabled=false
        - xpack.graph.enabled=false
        - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - gl_esdata1:/usr/share/elasticsearch/data
    tty: true
    ports:
      - 9200
      - 9300
    networks:
      - glnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.13
    container_name: elasticsearch2
    hostname: elasticsearch2
    environment:
      - cluster.name=graylog-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.security.audit.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - discovery.zen.ping.unicast.hosts=elasticsearch1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - gl_esdata2:/usr/share/elasticsearch/data
    tty: true
    networks:
      - glnet
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.13
    container_name: kibana
    hostname: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch1:9200
    tty: true
    networks:
      - glnet
    ports:
      - 5601
    depends_on:
      - elasticsearch1
      - elasticsearch2
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.0
    container_name: graylog
    volumes:
      - gl_graylog_journal:/usr/share/graylog/data/journal
      - ./graylog/config:/usr/share/graylog/data/config
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
      - ELASTICSEARCH_HOSTS=elasticsearch1
    links:
      - mongodb:mongo
      - elasticsearch1
      - elasticsearch2
    depends_on:
      - mongodb
      - elasticsearch1
      - elasticsearch2
    ports:
      # Graylog web interface and REST API
      - 9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - glnet
volumes:
  gl_esdata1:
    driver: local
  gl_esdata2:
    driver: local
  gl_mongo_data:
    driver: local
  gl_graylog_journal:
    driver: local

networks:
  glnet:
